accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
	path('signup/', views.SignUpView.as_view(), name='signup'),
	path('login/', views.UserLoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(next_page='photos:home'), name='logout'),
	path('signup/', views.SignUpView.as_view(), name='signup'),
	path('contact/', views.ContactFormView.as_view(), name='contact'),
	path('messages/send-message/', views.send_message, name='send_message'),
	path('messages/', views.ContactMessageListView.as_view(), name='messages'),
	path('messages/<int:pk>/', views.ContactMessageDetailView.as_view(), name='message'),
	path('delete-message/<int:pk>/', views.ContactMessageDeleteView.as_view(), name='delete_message'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
	path('', views.PostListView.as_view(), name='home'),
	path('user/<str:username>/', views.UserPostListView.as_view(), name='user_posts'),
	path('<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
	path('create/', views.PostCreateWithInlinesView.as_view(), name='create'),
	path('create-bulk/', views.PostCreateView.as_view(), name='create_bulk'),
	path('update/<slug:slug>', views.PostUpdateWithInlinesView.as_view(), name='update'),
	path('delete/<slug:slug>', views.PostDeleteView.as_view(), name='delete'),
	path('<slug:slug>/add-tags/', views.add_tags_to_post, name='add_tags'),
	path('tag/<str:tag>', views.search_posts_by_tag, name='search_by_tag'),
]

photography_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# import debug_toolbar

urlpatterns = [
				  path('admin/', admin.site.urls),
				  # path('__debug__/', include(debug_toolbar.urls)),
				  path('accounts/', include('accounts.urls', namespace='accounts')),
				  path('accounts/', include('django.contrib.auth.urls')),
				  path('', include('photos.urls', namespace='photos')),
				  path('blog/', include('blog.urls', namespace='blog')),
				  path(r'comments/', include('django_comments_xtd.urls')),
			  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Django Photography"
admin.site.site_title = "Django Photography"

# if settings.DEBUG:
# 	from django.conf.urls.static import static
# 	import debug_toolbar
# 	import mimetypes
#
# 	mimetypes.add_type("application/javascript", ".js", True)
#
# 	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# 	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# 	urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
#
# SHOW_TOOLBAR_CALLBACK = True

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from photos.models import AlbumToken, Photo, Album


class CustomUser(AbstractUser):
	# class created for eventuality of needing additional fields for user
	pass

	def __str__(self):
		return self.username


class ContactMessage(models.Model):
	name = models.CharField(max_length=255)
	email = models.EmailField()
	message = models.TextField()
	date_sent = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, ContactMessage


class CustomUserCreationForm(UserCreationForm):
	class Meta:
		model = CustomUser
		fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):
	class Meta:
		model = CustomUser
		fields = ('username', 'email')


class ContactMessageForm(forms.ModelForm):
	class Meta:
		model = ContactMessage
		exclude = ('date_sent',)

accounts/views.py
from _ast import Delete

from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, FormView, DeleteView

from .forms import CustomUserCreationForm, ContactMessageForm
from .models import ContactMessage


class UserLoginView(LoginView):
	template_name = 'registration/login.html'
	fields = '__all__'
	redirect_authenticated_user = True

	def get_success_url(self):
		return reverse_lazy('photos:home')


class SignUpView(CreateView):
	template_name = 'registration/signup.html'
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('photos:home')

	def form_valid(self, form):
		user = form.save()
		if user is not None:
			login(self.request, user)
		return super(SignUpView, self).form_valid(form)


def send_message(request):
	if request.is_ajax():
		name = request.POST.get('name', None)
		# email = request.POST.get('email', None)
		# message = request.POST.get('message', None)
		contact_form = ContactMessageForm(request.POST)
		if contact_form.is_valid():
			contact_form.save()
			return JsonResponse({'msg': f'Thank you {name}! Your message was successfully sent!'})

		return JsonResponse({'msg': 'There was an error sending your message.'})


class ContactFormView(FormView):
	template_name = 'photos/index.html'
	form_class = ContactMessageForm
	success_url = 'photos:home'

	def form_valid(self, form):
		return super().form_valid(form)


class ContactMessageListView(ListView):
	model = ContactMessage
	template_name = 'accounts/message_list.html'
	context_object_name = 'messages'
	ordering = ['-date_sent']

	def get_queryset(self):
		qs = super().get_queryset()
		if self.request.user.is_staff:
			return qs
		return None


class ContactMessageDetailView(DetailView):
	model = ContactMessage
	template_name = 'accounts/message_detail.html'
	context_object_name = 'message'


class ContactMessageDeleteView(DeleteView):
	model = ContactMessage
	success_url = reverse_lazy('accounts:messages')
	template_name = 'accounts/contact_message_confirm_delete.html'
	context_object_name = 'message'

templates/accounts/contact_message_confirm_delete.html
{% extends '_base.html' %}

{% block title %}
    Confirm Message Delete
{% endblock %}


{% block content %}
    <div class="global-container">

        <div class="row justify-content-md-center mt-30">
            <div class="col-lg-6 white-box p-4">


                <form method="POST">
                    {% csrf_token %}
                    <h3>Are you sure you want to delete this message from <b>{{ message.name|title }}</b>?</h3>
                    <div class="d-flex justify-content-between mt-3">
                        <a class="btn btn-outline-secondary btn-sm" href="{% url 'accounts:message' message.pk %}">Back</a>
                        <input type="submit" class="btn btn-danger btn-sm" value="Delete"/>
                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/message_detail.html
{% extends '_base.html' %}

{% block title %}
    Message from {{ message.name|title }}
{% endblock %}

{% block content %}

    <div class="global-container text-center">

        <div class="col-xl-8 col-lg-10 white-box mx-auto">

            <h2>Message from {{ message.name|title }}</h2>
            <hr class="half-gradient-hr">
            <h6 class="mb-5">Sent on <b>{{ message.date_sent|date:"d M Y" }}</b> at
                <b>{{ message.date_sent|date:"G:i" }}</b>
            </h6>

            <div class="p-3 text-start">
                <div class="bg-light p-2" style="border-radius: 8px;">
                    <p class="lead">{{ message.message }}</p>
                </div>
                <div class="d-flex justify-content-between mt-5">
                    {% if request.user.is_authenticated and request.user.is_staff %}
                        <div>
                            <a class="btn btn-danger btn-sm" href="{% url 'accounts:delete_message' message.pk %}">Delete
                                message
                            </a>
                        </div>
                    {% endif %}
                    <div>
                        <button onclick="window.location.href='{% url 'accounts:messages' %}'" style="min-width:120px;"
                                class="btn btn-outline-secondary btn-sm">Back to Messages
                        </button>
                        <button type="submit" class="btn btn-success btn-sm ml-2"
                                onclick="location.href='mailto:{{ message.email }}?subject=Reply:&nbsp;{{ message.message|truncatewords:12 }}';"
                                style="min-width:120px; margin-left:10px;">Reply
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/accounts/message_list.html
{% extends '_base.html' %}

{% block title %}
    Messages
{% endblock %}

{% block content %}
    <div class="global-container text-center">
        <div class="col-xl-8 col-lg-10 white-box mx-auto">

            <h1 class="subheading">Messages</h1>
            <hr class="half-gradient-hr mb-5">

            <div class="table-responsive">
                <table class="table align-middle table-hover">
                    <thead class="table-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Date Sent</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Message</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for message in messages %}
                        <tr class='clickable-row'
                            data-href={% url 'accounts:message' message.pk %} style="cursor:pointer;">
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ message.date_sent|date:"d M Y, G:i" }}</td>
                            <td>{{ message.name }}</td>
                            <td>{{ message.email }}</td>
                            <td class="text-start">{{ message.message|truncatewords:33 }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    <script>
        $(".clickable-row").click(function () {
            window.location = $(this).data("href");
        });
    </script>
{% endblock javascript %}