accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
	path('signup/', views.SignUpView.as_view(), name='signup'),
	path('login/', views.UserLoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(next_page='photos:home'), name='logout'),
	path('signup/', views.SignUpView.as_view(), name='signup'),
	path('contact/', views.ContactFormView.as_view(), name='contact'),
	path('messages/send-message/', views.send_message, name='send_message'),
	path('messages/', views.ContactMessageListView.as_view(), name='messages'),
	path('messages/<int:pk>/', views.ContactMessageDetailView.as_view(), name='message'),
	path('delete-message/<int:pk>/', views.ContactMessageDeleteView.as_view(), name='delete_message'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
	path('', views.PostListView.as_view(), name='home'),
	path('user/<str:username>/', views.UserPostListView.as_view(), name='user_posts'),
	path('<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
	path('create/', views.PostCreateWithInlinesView.as_view(), name='create'),
	path('create-bulk/', views.PostCreateView.as_view(), name='create_bulk'),
	path('update/<slug:slug>', views.PostUpdateWithInlinesView.as_view(), name='update'),
	path('delete/<slug:slug>', views.PostDeleteView.as_view(), name='delete'),
	path('<slug:slug>/add-tags/', views.add_tags_to_post, name='add_tags'),
	path('tag/<str:tag>', views.search_posts_by_tag, name='search_by_tag'),
]

photography_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# import debug_toolbar

urlpatterns = [
				  path('admin/', admin.site.urls),
				  # path('__debug__/', include(debug_toolbar.urls)),
				  path('accounts/', include('accounts.urls', namespace='accounts')),
				  path('accounts/', include('django.contrib.auth.urls')),
				  path('', include('photos.urls', namespace='photos')),
				  path('blog/', include('blog.urls', namespace='blog')),
				  path(r'comments/', include('django_comments_xtd.urls')),
			  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Django Photography"
admin.site.site_title = "Django Photography"

# if settings.DEBUG:
# 	from django.conf.urls.static import static
# 	import debug_toolbar
# 	import mimetypes
#
# 	mimetypes.add_type("application/javascript", ".js", True)
#
# 	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# 	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# 	urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
#
# SHOW_TOOLBAR_CALLBACK = True

photos/urls.py
from django.urls import path
from . import views

app_name = 'photos'

urlpatterns = [
	path('', views.HomePageView.as_view(), name='home'),
	path('photos/<int:pk>/', views.PhotoDetailView.as_view(), name='photo_detail'),
	path('photos/', views.PhotoListView.as_view(), name='photo_list'),
	path('photos/add/', views.PhotoCreateView.as_view(), name='add_photos'),
	path('photos/add-photo/', views.upload_photo, name='add_photo'),

	path('albums/', views.AlbumListView.as_view(), name='albums'),
	path('albums/<slug:slug>', views.AlbumDetailView.as_view(), name='album_detail'),
	path('albums/create/', views.AlbumCreateWithInlinesView.as_view(), name='album_create'),
	path('albums/create-bulk/', views.AlbumCreateView.as_view(), name='album_create_bulk'),
	path('albums/update/<slug:slug>', views.AlbumUpdateWithInlinesView.as_view(), name='album_update'),
	path('albums/delete/<slug:slug>', views.AlbumDeleteView.as_view(), name='album_delete'),

	path('search/', views.SearchView.as_view(), name='search'),

	path('private/<str:token>/', views.PrivateAlbumView.as_view(), name='private_album'),
	path('private-albums/', views.PrivateAlbumListView.as_view(), name='private_albums'),
	path('create-token/<slug:slug>/', views.create_token, name='create_token'),
	path('update-token/<int:pk>/', views.update_token, name='update_token'),
	path('delete-token/<int:pk>/', views.delete_token, name='delete_token'),

	path('like-photo/', views.like_photo, name='like_photo'),

]

templates/includes/_home_navbar.html
<nav class="nav main-nav">
    <div class="container">
        <div class="logo">
            <a href="{% url 'photos:home' %}">Django Photography</a>
        </div>
        <div id="mainListDiv" class="main_list">
            <ul class="navlinks">
                <li><a href="{% url 'blog:home' %}">Blog</a></li>
                <li><a href="{% url 'photos:albums' %}">Albums</a></li>
                <li><a href="{% url 'photos:photo_list' %}">Galleries</a></li>
                <li><a href="{% url 'photos:home' %}#contact-form">Contact</a></li>
                <li>
                    <form class="search-box d-flex">
                        <form>
                            <input class="search_bar" name="search_bar" type="search">
                        </form>
                        {#                        <a class="p-20 cursor-pointer"><i class="bi bi-search"></i></a>#}
                        {#                        <button class="btn btn-outline-success" type="submit">Search</button>#}
                    </form>
                </li>
            </ul>
        </div>
        <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
    </div>
</nav>

templates/includes/_navbar.html
<nav class="nav main-nav">
    <div class="container">
        <div class="logo">
            <a href="{% url 'photos:home' %}">Django Photography</a>
        </div>
        <div id="mainListDiv" class="main_list">
            <ul class="navlinks">
                <li><a href="{% url 'blog:home' %}">Blog</a></li>
                <li><a href="{% url 'photos:albums' %}">Portfolio</a></li>
                {#                <li><a href="{% url 'photos:home' %}#contact-form">Contact</a></li>#}

                <li><a data-bs-toggle="modal"
                       href="#contactMessageModal"
                       role="button">Contact</a></li>

                {% if request.user.is_authenticated %}
                    <li>
                        <a href="#"
                           id="user-menu"
                           data-bs-toggle="popover"
                           data-bs-trigger="focus"
                           html="true"
                           data-html="true"

                           title="{{ request.user.username|title }}"

                           data-bs-content="<ul>
                                            <li><a href='{% url 'accounts:messages' %}'>Messages</a></li>
                                            <li><a href='{% url 'photos:private_albums' %}'>Private albums</a></li>
                                            <li><a href='{% url 'blog:create_bulk' %}'>Create Post</a></li>
                                            <li><a href='{% url 'photos:album_create_bulk' %}'>Create Album</a></li>
                                            <li><a href='{% url 'accounts:logout' %}'>Logout <i class='bi bi-box-arrow-right'></i></a></li>
                                        </ul>"

                           data-bs-placement="bottom">
                            <i class="bi bi-person" style="font-size: 1.5rem;"></i>
                        </a>
                    </li>
                {% endif %}
                <li>
                    <div>
                        <form class="search-box d-flex justify-content-center" method="get"
                              action="{% url 'photos:search' %}" autocomplete="off">
                            <input class="search_bar" name="q" type="search" value='{{ request.GET.q }}'>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
        <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
    </div>
</nav>

<!-- Contact Message Modal -->
<div class="modal fade" id="contactMessageModal" tabindex="-1" aria-labelledby="contactMessageModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-light py-2 px-4">
                <h1 class="modal-title" id="contactMessageModalLabel">Send me a message</h1>
                <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body m-2">

                <form id="contact-form" method="post" class="row">
                    {% csrf_token %}

                    <div class="col-6">
                        <div class="form-floating">
                            <input type="text" class="form-control" id="contact-form-name" name="name"
                                   placeholder="Name" required>
                            <label for="contact-form-name">Name</label>
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="form-floating">
                            <input type="email" class="form-control" id="contact-form-email" name="email"
                                   placeholder="Email" required>
                            <label for="contact-form-email">Email address</label>
                        </div>
                    </div>

                    <div class="col-12 mt-3">
                        <div class="form-floating">
                        <textarea class="form-control" placeholder="Leave a comment here" id="contact-form-message"
                                  name="message" style="height: 200px" required></textarea>
                            <label for="contact-form-message">Message</label>
                        </div>
                    </div>

                    <div class="col-12 mt-3">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success float-end" id="send-message"
                                data-bs-dismiss="modal">Send message
                        </button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

templates/includes/contact_form.html
{% load crispy_forms_tags %}

<div class="row justify-content-md-center">
    <div class="col-xl-7 col-lg-7 col-md-10">

        <div class="contact-form-container">

            <form id="contact-form" method="post" class="row mb-3">
                <h1 class="text-center mb-3">Contact me</h1>
                {% csrf_token %}

                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                <div class="col-6">
                    {{ form.name|as_crispy_field }}
                </div>

                <div class="col-6">
                    {{ form.email|as_crispy_field }}
                </div>

                <div class="col-12">
                    {{ form.message|as_crispy_field }}
                </div>

                <div>
                    <button type="submit" class="btn btn-primary float-end mt-3">Send Message</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/includes/footer.html
<footer class="text-center text-white main-footer" style="margin-top: auto;">

    <div class="container pt-2">

        <section class="mb-2">
            <a class="btn btn-link btn-floating btn-lg text-dark m-1"
               href="https://www.facebook.com/django-photography"
               role="button"
               data-mdb-ripple-color="dark"><i class="fab fa-facebook-f"></i></a>
            <a class="btn btn-link btn-floating btn-lg text-dark m-1"
               href="https://twitter.com/djangophotography"
               role="button"
               data-mdb-ripple-color="dark"
            ><i class="fab fa-twitter"></i
            ></a>
            <a class="btn btn-link btn-floating btn-lg text-dark m-1"
               href="https://www.instagram.com/"
               role="button"
               data-mdb-ripple-color="dark"
            ><i class="fab fa-instagram"></i></a>

        </section>
    </div>

    <div class="text-center text-dark p-3" style="background-color: rgba(236,233,230,0.42);">
        <span>© {% now 'Y' %} Copyright:</span>
        <a class="text-dark footer-link" href="#">Django Photography</a>
        &nbsp;&nbsp;<a href="{% url 'accounts:login' %}" class="footer-link">
        <i class="bi bi-box-arrow-in-right" style="font-size:16px;"></i>
    </a>
    </div>

</footer>

templates/includes/header.html
{% load static %}

<div style="background: url('{% static 'images/colibita2.jpg' %}')" class="jumbotron bg-cover text-white">
    <div class="container py-5 d-flex align-items-center justify-content-center header-heading">
        <div>
            <h1 class="display-1 font-weight-bold main-heading">live, lough, love</h1><br>
            <h1 class="display-1 font-weight-bold sub-heading">remember</h1>

        </div>
    </div>
</div>

templates/includes/homepage_carousel.html
{% load static %}


<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="url('{% static 'images/colibita.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="url('{% static 'images/colibita2.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="url('{% static 'images/colibita3.jpg' %}" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

templates/includes/messages.html
{% if messages %}
    <div class="row justify-content-md-center mt-100 py-3">
        <div class="col-xl-7 col-lg-9 px-4">
            {% for message in messages %}
                {% ifchanged %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        <p style="margin-bottom: 0; font-size: 1.2em;">{{ message|safe }}</p>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endifchanged %}
            {% endfor %}
        </div>
    </div>
{% endif %}

templates/includes/small_header.html
{% load static %}

<div style="background: url('{% static 'images/colibita2.jpg' %}')" class="bg-cover-small">
    <div class="container py-5 d-flex align-items-center justify-content-center header-heading">
        <div>
        </div>
    </div>
</div>