blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
	path('', views.PostListView.as_view(), name='home'),
	path('user/<str:username>/', views.UserPostListView.as_view(), name='user_posts'),
	path('<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
	path('create/', views.PostCreateWithInlinesView.as_view(), name='create'),
	path('create-bulk/', views.PostCreateView.as_view(), name='create_bulk'),
	path('update/<slug:slug>', views.PostUpdateWithInlinesView.as_view(), name='update'),
	path('delete/<slug:slug>', views.PostDeleteView.as_view(), name='delete'),
	path('<slug:slug>/add-tags/', views.add_tags_to_post, name='add_tags'),
	path('tag/<str:tag>', views.search_posts_by_tag, name='search_by_tag'),
]

photography_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# import debug_toolbar

urlpatterns = [
				  path('admin/', admin.site.urls),
				  # path('__debug__/', include(debug_toolbar.urls)),
				  path('accounts/', include('accounts.urls', namespace='accounts')),
				  path('accounts/', include('django.contrib.auth.urls')),
				  path('', include('photos.urls', namespace='photos')),
				  path('blog/', include('blog.urls', namespace='blog')),
				  path(r'comments/', include('django_comments_xtd.urls')),
			  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Django Photography"
admin.site.site_title = "Django Photography"

# if settings.DEBUG:
# 	from django.conf.urls.static import static
# 	import debug_toolbar
# 	import mimetypes
#
# 	mimetypes.add_type("application/javascript", ".js", True)
#
# 	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# 	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# 	urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
#
# SHOW_TOOLBAR_CALLBACK = True

blog/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

from taggit.managers import TaggableManager

from photography_website import settings
from core.models import BasePublishModel
from core.utils import slugify_pre_save


class Post(BasePublishModel):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
	title = models.CharField(max_length=255)
	text = models.TextField(null=True, blank=True)
	slug = models.SlugField(null=True, blank=True, db_index=True)
	tags = TaggableManager(blank=True)

	def get_featured_image_url(self):
		images = self.post_photos.all()
		if images.exists():
			try:
				featured_image = images.filter(is_featured=True).first()
				return featured_image.image.url
			except:
				featured_image = images.first()
				return featured_image.image.url
		else:
			return ''

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.slug])

	def __str__(self):
		return self.title

	class Meta:
		ordering = ['-updated_on', '-created_on']
		verbose_name = 'Post'
		verbose_name_plural = 'Posts'


pre_save.connect(slugify_pre_save, sender=Post)

blog/forms.py
from django import forms

from .models import Post
from photos.models import Photo, Album


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'status', 'text', 'tags']
		widgets = {
			'title': forms.TextInput(attrs={
			}),
			'status': forms.Select(),
			'text': forms.Textarea(attrs={
				'placeholder': 'Add post text here',
				'rows': 7,
				'cols': 70
			}),
		}


class PhotoForm(forms.ModelForm):
	class Meta:
		model = Photo
		fields = ['image', 'description', 'is_featured']
		widgets = {
			'image': forms.FileInput(attrs={
				'style': 'width: 240px;'
			}),
			'description': forms.Textarea(attrs={
				'placeholder': 'Add a short photo description that will be displayed below the photo (optional)',
				'rows': 1,
				'cols': 70
			}),
		}


class SelectAlbumForm(forms.Form):
	album = forms.ModelChoiceField(queryset=Album.objects.all())

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, ListView, CreateView, DeleteView
from django.contrib import messages

from hitcount.views import HitCountDetailView
from extra_views import InlineFormSetFactory, CreateWithInlinesView, UpdateWithInlinesView, SuccessMessageMixin

from photos.models import Photo, Album
from .forms import PostForm, PhotoForm
from .models import Post


class PostDetailView(HitCountDetailView):
	template_name = 'blog/post_details.html'
	model = Post
	context_object_name = 'post'
	count_hit = True

	def get_object(self, queryset=None):
		if queryset is None:
			queryset = self.get_queryset()
		slug = self.kwargs.get(self.slug_url_kwarg)
		post = get_object_or_404(Post, slug=slug)
		if self.request.user.is_staff:
			return post
		if post.status == 'PR':
			messages.error(self.request, "This post is private")
			return Post.objects.none()
		elif post.status == 'DR':
			messages.warning(self.request, "This post is not yet published")
			return Post.objects.none()
		else:
			return post


class PostListView(ListView):
	template_name = 'blog/post_list.html'
	model = Post
	context_object_name = 'posts'

	def get_queryset(self):
		qs = super().get_queryset()
		if self.request.user.is_staff:
			return qs
		return qs.filter(status='PU')


class UserPostListView(ListView):
	template_name = 'blog/user_post_list.html'
	model = Post
	context_object_name = 'posts'

	def get_queryset(self):
		qs = super().get_queryset()
		user_posts = qs.filter(author=self.request.user)
		return user_posts


class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
	model = Post
	success_url = reverse_lazy('blog:home')
	permission_required = 'post.delete_post'


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
	model = Post
	template_name = 'blog/post_create_bulk.html'
	form_class = PostForm
	success_url = None
	permission_required = 'post.add_post'

	def form_valid(self, form):
		form.instance.author = self.request.user
		self.object = form.save()
		photos = self.request.FILES.getlist('photos')
		if photos:
			new_album = Album.objects.create(title=self.object.title) if 'new_album' in self.request.POST else None
			for photo in photos:
				new_photo = Photo.objects.create(
					album=new_album,
					post=self.object,
					tags=self.object.tags,
					image=photo
				)
		messages.success(self.request, f"<b>{self.object.title}</b> created successfully")
		return HttpResponseRedirect(self.get_success_url())

	def get_success_url(self):
		return reverse_lazy('blog:post_detail', kwargs={'slug': self.object.slug})


class PostPhotoInlineFormset(InlineFormSetFactory):
	model = Photo
	form_class = PhotoForm
	fields = ['image', 'description', 'is_featured']
	extra_forms = 1
	can_delete = True

	def get_factory_kwargs(self):
		factory_kwargs = super().get_factory_kwargs()
		factory_kwargs.update({'extra': self.extra_forms})
		return factory_kwargs


class PostCreateWithInlinesView(LoginRequiredMixin, CreateWithInlinesView):
	model = Post
	form_class = PostForm
	inlines = [PostPhotoInlineFormset, ]
	template_name = 'blog/post_create.html'
	success_url = None

	def forms_valid(self, form, inlines):
		form.instance.author = self.request.user
		self.object = form.save()
		response = self.form_valid(form)
		new_album = Album.objects.create(title=self.object.title) if 'new_album' in self.request.POST else None
		for formset in inlines:
			for form in formset:
				new_photo = form.save(commit=False)
				new_photo.album = new_album
				new_photo.save()
		messages.success(self.request, f"<b>{self.object.title}</b> created successfully")
		return response

	def get_success_url(self):
		return reverse_lazy('blog:post_detail', kwargs={'slug': self.object.slug})


class PostUpdateWithInlinesView(LoginRequiredMixin, SuccessMessageMixin, UpdateWithInlinesView):
	model = Post
	form_class = PostForm
	inlines = [PostPhotoInlineFormset, ]
	template_name = 'blog/post_update.html'
	success_message = "<b>%(title)s</b> was updated successfully"


@login_required
def add_tags_to_post(request, slug):
	post = get_object_or_404(Post, slug=slug)
	new_tags = request.POST.get('new_tags')
	tag_list = [raw_tag.strip() for raw_tag in new_tags.split(',')]
	for tag in tag_list:
		post.tags.add(tag)
	if len(tag_list) == 1:
		messages.success(request, f"The tag <b>{tag_list[0]}</b> was added to post <b>{post.title}</b>")
	elif len(tag_list) > 1:
		messages.success(request, f"The tags <b>{', '.join(tag_list)}</b> were added to post <b>{post.title}</b>")
	return redirect('blog:post_detail', slug=post.slug)


def search_posts_by_tag(request, tag):
	posts = Post.objects.published().filter(tags__name=tag)
	context = {'tag': tag, 'posts': posts}
	if posts.exists():
		messages.info(request, f"Posts tagged with <b>{tag}</b>")
	else:
		messages.warning(request, f"There are no posts tagged with <b>{tag}</b>")
	return render(request, 'blog/post_list.html', context)

templates/blog/formset.html
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

<table>
    {{ formset.management_form|crispy }}

    {% for form in formset.forms %}
        <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
            {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}

                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}

</table>
<br>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="{% static 'js/jquery.formset.js' %}">
</script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>

templates/blog/post_confirm_delete.html
{% extends '_base.html' %}

{% block title %}
    Confirm Post Delete
{% endblock %}


{% block content %}
    <div class="global-container">

        <div class="row justify-content-md-center mt-30">
            <div class="col-lg-8 col-md-10 white-box">

                <h3><a style="text-decoration: none;" href="{{ post.get_absolute_url }}">&#8592; Go Back</a></h3>
                <form method="POST">
                    {% csrf_token %}
                    <h3>Are you sure you want to delete the post <b>{{ post.title|title }}</b>?</h3>
                    <input type="submit" class="btn btn-danger" value="Delete"/>
                </form>

            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/post_creaate_from_album.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create Post
{% endblock %}

{% block content %}
    <div class="global-container">
        {% include 'includes/messages.html' %}

        <div class="row justify-content-md-center mt-90">
            <div class="col-xl-8 col-lg-9 col-md-10">

                <form action="" method="post" class="row g-3 mb-3 white-box" enctype="multipart/form-data">
                    <h2 class="mb-3 text-center">Create <b>New Post</b></h2>
                    <ul class="nav nav-tabs nav-pills nav-fill mb-5">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'create_post' %}">Bulk photo upload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">One-by-one photo upload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="#">From existing album</a>
                        </li>
                    </ul>
                    {% csrf_token %}

                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    <div class="col-10">
                        {{ form.title|as_crispy_field }}
                    </div>

                    <div class="col-2">
                        {{ form.status|as_crispy_field }}
                    </div>

                    <div class="col-12">
                        {{ form.text|as_crispy_field }}
                    </div>

                    <div class="col-12">
                        {{ form.tags|as_crispy_field }}
                    </div>
                    <h3 class="py-2">Post Photos</h3>

                    <!-- Post Photos -->

                {% crispy select_album_form %}

                    <div class="col-lg-12 mt-3">
                        <div class="row">
                            <div class="col-2">
                                <a href="{% url 'blog' %}"
                                   class="btn btn-outline-secondary w-100 mb-3">Cancel</a>
                            </div>
                            <div class="col-10">
                                <button type="submit" class="btn btn-success w-100 mb-3">Create Post</button>
                            </div>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/post_create.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create Post{% endblock %}

{% block content %}
    <div class="global-container">
        {% include 'includes/messages.html' %}

        <div class="row justify-content-md-center">
            <div class="col-xl-8 col-lg-9 col-md-10">

                <form action="" method="post" class="row g-3 mb-3 white-box"
                      enctype="multipart/form-data">
                    <h2 class="mb-0 text-center">Create <b>New Post</b></h2>
                    <div class="col-12">
                        <hr class="half-gradient-hr">
                    </div>

                    <div class="col-12">
                        <ul class="list-group list-group-horizontal">
                            <li class="list-group-item list-group-item-action list-group-item-light w-50 text-center">
                                <a href="{% url 'blog:create_bulk' %}" style="text-decoration: none; color: black;">Bulk
                                    photo upload</a>
                            </li>
                            <li class="list-group-item list-group-item-action list-group-item-warning w-50 text-center">
                                <a href="{% url 'blog:create' %}"
                                   style="text-decoration: none; color: black; font-weight: bold;">One-by-one photo
                                    upload</a>
                            </li>
                        </ul>
                    </div>

                    {% csrf_token %}

                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    <div class="col-10">
                        {{ form.title|as_crispy_field }}
                    </div>

                    <div class="col-2">
                        {{ form.status|as_crispy_field }}
                    </div>

                    <div class="col-12">
                        {{ form.text|as_crispy_field }}
                    </div>

                    <div class="col-12">
                        {{ form.tags|as_crispy_field }}
                    </div>

                    <div class="col-12">
                        <h3 class="mt-2 text-center">Post Photos</h3>
                    </div>
                    <hr class="half-gradient-hr">
                    <div class="form-group py-2">
                        <input type="checkbox" class="form-check-input" name="new_album" id="new-album" checked>
                        <label class="form-check-label" for="new-album">Create a new album with this post photos</label>
                    </div>

                    <div class="col-12">
                        <div class="row" id="post_form">

                            {% for formset in inlines %}
                                {{ formset.management_form }}
                                {{ formset|as_crispy_errors }}

                                {% for photo_form in formset %}

                                    <div class="col-md-12 col-lg-6 p-2 d-inline-flex align-self-stretch image-form">
                                        <div class="form-photo-box w-100">
                                            <div class="d-flex justify-content-between pt-2 px-2">
                                                <div><b>Add a photo</b></div>
                                                <i class="bi bi-x-lg delete-image-form" data-tooltip="Remove form"></i>
                                            </div>
                                            <div class="p-2">
                                                {{ photo_form|crispy }}
                                            </div>

                                        </div>
                                    </div>

                                    <div id="form-end-hidden" style="display: none;"></div>
                                {% endfor %}
                                <div class="col-12">
                                    <button id="add-image-form" class="btn btn-link my-2" style="text-decoration: none;"
                                            data-tooltip="Add another photo"><i class="bi bi-plus-lg"></i></button>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="col-lg-12 mt-2">
                        <div class="d-flex justify-content-between py-2">
                            <a href="{% url 'blog:home' %}" style="width:200px; min-width:75px;"
                               class="btn btn-outline-secondary">Cancel</a>
                            <button type="submit" class="btn btn-success ml-2"
                                    style="width:100%; min-width:120px; margin-left:10px;">Create Post
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/post_create_bulk.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create Post
{% endblock %}

{% block content %}
    <div class="global-container">
        {% include 'includes/messages.html' %}

        <div class="row justify-content-md-center">
            <div class="col-xl-8 col-lg-9 col-md-10">

                <form action="" method="post" class="row g-3 mb-3 white-box" enctype="multipart/form-data">
                    <h2 class="mb-0 text-center">Create <b>New Post</b></h2>
                    <div class="col-12">
                        <hr class="half-gradient-hr">
                    </div>

                    <ul class="list-group list-group-horizontal">
                        <li class="list-group-item  list-group-item-action list-group-item-warning w-100 text-center">
                            <a href="{% url 'blog:create_bulk' %}"
                               style="text-decoration: none; color: black; font-weight: bold;">Bulk photo upload</a>
                        </li>
                        <li class="list-group-item list-group-item-action list-group-item-light w-100 text-center">
                            <a href="{% url 'blog:create' %}" style="text-decoration: none; color: black;">One-by-one
                                photo upload</a>
                        </li>
                    </ul>

                    {% csrf_token %}

                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    <div class="col-10">
                        {{ form.title|as_crispy_field }}
                    </div>

                    <div class="col-2">
                        {{ form.status|as_crispy_field }}
                    </div>

                    <div class="col-12">
                        {{ form.text|as_crispy_field }}
                    </div>

                    <div class="col-12">
                        {{ form.tags|as_crispy_field }}
                    </div>

                    <!-- Post Photos -->
                    <div class="col-12">
                        <h3 class="mt-2 text-center">Post Photos</h3>
                        <hr class="half-gradient-hr">
                        <div class="form-group py-2">
                            <input type="checkbox" class="form-check-input" name="new_album" id="new-album" checked>
                            <label class="form-check-label" for="new-album">Create a new album with this post
                                photos</label>
                        </div>

                        <input class="form-control form-control-lg" type="file" accept="image/*" id="photos"
                               name="photos"
                               multiple>
                        {% for error in form.photos.errors %}
                            <small class="text-danger ml-2">{{ error }}</small>
                        {% endfor %}
                    </div>

                    <div class="col-lg-12 mt-3">
                        <div class="d-flex justify-content-between py-2">
                            <a href="{% url 'blog:home' %}" style="width:200px; min-width:75px;"
                               class="btn btn-outline-secondary">Cancel</a>
                            <button type="submit" class="btn btn-success ml-2"
                                    style="width:100%; min-width:120px; margin-left:10px;">Create Post
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/blog/post_details.html
{% extends '_base.html' %}
{% load comments comments_xtd social_share hitcount_tags %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}

    {% if post %}
        <div class="row justify-content-md-center">

            <div class="col-lg-12">
                <div class="post-header-img"
                     style="background-image: url({{ post.get_featured_image_url }}); background-size: cover;">

                    <!-- Post Title Section -->
                    <div class="post-info-container text-center px-3 px-sm-5 py-1 py-sm-3">
                        <h1>{{ post.title }}</h1>
                        <hr class="half-gradient-hr">
                        <h6>By <b>{{ post.author|title }}</b>
                            on <b>{{ post.created_on|date:"d M Y" }}</b>&#8201;&#8201;
                            {% get_comment_count for object as comment_count %}
                            {{ comment_count }}&#8201;<i class="bi bi-chat"
                                                         data-tooltip="{{ comment_count }} comment{{ comment_count|pluralize }}"></i>&#8201;
                            {% get_hit_count for post as hit_count %}
                            {{ hit_count }}&#8201;<i class="bi bi-eye-fill"
                                                     data-tooltip="{{ hit_count }} view{{ hit_count|pluralize }}"></i>
                        </h6>

                        <!-- Post Tags Section -->
                        {% for tag in post.tags.all %}
                            <div class="post-action-tag" data-tooltip="See posts with this tag">
                        <span class="badge rounded-pill bg-secondary"
                              style="font-size: calc(0.5vw + 7px); cursor: pointer;"><a
                                href="{% url 'blog:search_by_tag' tag %}"
                                style="text-decoration: none; color: #fff;">{{ tag }}</a></span>
                            </div>
                        {% endfor %}

                        {% if request.user.is_authenticated and request.user.is_staff %}
                            <div id="tag-form" class="post-action-form" data-tooltip="Add tags">
                                <form action="{% url 'blog:add_tags' post.slug %}" method="post"
                                      autocomplete="off">
                                    {% csrf_token %}
                                    <input type="text" name="new_tags">
                                    <input type="submit" hidden/>
                                </form>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>

            <!-- Messages Section -->
            <div class="col-lg-9 text-center mb-0">
                {% include 'includes/messages.html' %}
            </div>

            <!-- Post Management Section -->
            <div class="col-lg-7 text-center mt-3">
                {% if request.user.is_authenticated and request.user.is_staff %}
                    <div class="d-flex justify-content-center align-items-center mt-2">
                        <a class="action-button edit-button" data-tooltip="Edit post"
                           href="{% url 'blog:update' post.slug %}">
                            <i class="bi bi-pencil-square"></i></a>

                        <a class="action-button delete-button" data-tooltip="Delete post"
                           href="{% url 'blog:delete' post.slug %}">
                            <i class="bi bi-trash"></i></a>
                    </div>
                {% endif %}

                <!-- Post Content Section -->
                {% if post.text %}
                    {% autoescape off %}
                        <div class="post-text mt-4">{{ post.text|linebreaks }}</div>
                    {% endautoescape on %}
                {% endif %}

                {% if post.post_photos %}
                    {% for photo in post.post_photos.all %}
                        <img src="{{ photo.image.url }}" alt="" style="width: 100%; padding: 7px;">
                        {% if photo.description %}
                            <h6>{{ photo.description|linebreaks }}</h6>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                {% if post.is_published %}
                    <div class="d-flex justify-content-center align-items-center">
                        {% post_to_facebook object_or_url "Share on Facebook" %}
                        {% post_to_whatsapp object_or_url "Share via WhatsApp" %}
                        {% save_to_pinterest object_or_url "Save to pinterest" %}
                    </div>
                {% endif %}
            </div>


            <!-- Comments Section -->
            <div class="col-lg-7 p-3">

                <div class="card card-block m-1">
                    <div class="card-body px-md-5">

                        <div class="py-4 text-center">
                            <a href="{% url 'blog:home' %}">Back to the post list</a>
                            &nbsp;&sdot;&nbsp;
                            {{ comment_count }} comment{{ comment_count|pluralize }}
                            ha{{ comment_count|pluralize:"s,ve" }} been posted.
                        </div>

                        {% if comment_count %}
                            <div class="comments">
                                {% render_xtdcomment_tree for post %}
                            </div>
                        {% endif %}
                        <h4 class="card-title text-center pb-3">Post your comment</h4>
                        {% render_comment_form for post %}
                    </div>
                </div>

                {% for object in object_list %}
                    ...
                    {% get_comment_count for object as comment_count %}
                    <p class="date">Published {{ object.publish }}
                        {% if comment_count %}
                            &sdot;&nbsp;{{ comment_count }} comment{{ comment_count|pluralize }}
                        {% endif %}
                    </p>
                    ...
                {% endfor %}
            </div>
            <!-- End Comments Section -->

        </div>
    {% endif %}
{% endblock %}

{% block javascript %}
    {% add_pinterest_script %}
{% endblock %}

templates/blog/post_inline_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Edit Post
{% endblock %}


{% block content %}
    {% include 'includes/small_header.html' %}


    <div class="container-fluid">
        <div class="d-flex align-items-center py-5">
            <div class="col-12 col-md-9 col-lg-6 mx-auto">

                <form action="" method="POST" enctype="multipart/form-data">

                    {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                    {% endfor %}

                    {% csrf_token %}

                    {{ form.management_form }}
                    {{ form.non_form_errors }}

                    <h3>Update Post</h3>

                    {{ post_form|crispy }}

                    {% for photo_form in form.forms %}
                        <hr>
                        <h5>
                            {% if photo_form.instance.id %}
                                Photo: {{ photo_form.instance.title|title }}<br>
                                <img src="{{ photo_form.instance.image.url }}" alt="" style="width: 100%; padding: 7px;">
                            {% else %}
                                {% if form.forms|length > 1 %}
                                    Add another photo
                                {% else %}
                                    Add a photo
                                {% endif %}
                            {% endif %}
                        </h5>

                        {% for hidden_field in photo_form.hidden_fields %}
                            {{ hidden_field.errors }}
                        {% endfor %}

                        {{ photo_form|crispy }}

                    {% endfor %}

                    <button type="submit" class="btn btn-success w-100 mb-3">Update Post</button>

                </form>
            </div>
        </div>
    </div>


{% endblock %}