blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
	path('', views.PostListView.as_view(), name='home'),
	path('user/<str:username>/', views.UserPostListView.as_view(), name='user_posts'),
	path('<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
	path('create/', views.PostCreateWithInlinesView.as_view(), name='create'),
	path('create-bulk/', views.PostCreateView.as_view(), name='create_bulk'),
	path('update/<slug:slug>', views.PostUpdateWithInlinesView.as_view(), name='update'),
	path('delete/<slug:slug>', views.PostDeleteView.as_view(), name='delete'),
	path('<slug:slug>/add-tags/', views.add_tags_to_post, name='add_tags'),
	path('tag/<str:tag>', views.search_posts_by_tag, name='search_by_tag'),
]

photography_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# import debug_toolbar

urlpatterns = [
				  path('admin/', admin.site.urls),
				  # path('__debug__/', include(debug_toolbar.urls)),
				  path('accounts/', include('accounts.urls', namespace='accounts')),
				  path('accounts/', include('django.contrib.auth.urls')),
				  path('', include('photos.urls', namespace='photos')),
				  path('blog/', include('blog.urls', namespace='blog')),
				  path(r'comments/', include('django_comments_xtd.urls')),
			  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Django Photography"
admin.site.site_title = "Django Photography"

# if settings.DEBUG:
# 	from django.conf.urls.static import static
# 	import debug_toolbar
# 	import mimetypes
#
# 	mimetypes.add_type("application/javascript", ".js", True)
#
# 	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# 	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# 	urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
#
# SHOW_TOOLBAR_CALLBACK = True

photos/urls.py
from django.urls import path
from . import views

app_name = 'photos'

urlpatterns = [
	path('', views.HomePageView.as_view(), name='home'),
	path('photos/<int:pk>/', views.PhotoDetailView.as_view(), name='photo_detail'),
	path('photos/', views.PhotoListView.as_view(), name='photo_list'),
	path('photos/add/', views.PhotoCreateView.as_view(), name='add_photos'),
	path('photos/add-photo/', views.upload_photo, name='add_photo'),

	path('albums/', views.AlbumListView.as_view(), name='albums'),
	path('albums/<slug:slug>', views.AlbumDetailView.as_view(), name='album_detail'),
	path('albums/create/', views.AlbumCreateWithInlinesView.as_view(), name='album_create'),
	path('albums/create-bulk/', views.AlbumCreateView.as_view(), name='album_create_bulk'),
	path('albums/update/<slug:slug>', views.AlbumUpdateWithInlinesView.as_view(), name='album_update'),
	path('albums/delete/<slug:slug>', views.AlbumDeleteView.as_view(), name='album_delete'),

	path('search/', views.SearchView.as_view(), name='search'),

	path('private/<str:token>/', views.PrivateAlbumView.as_view(), name='private_album'),
	path('private-albums/', views.PrivateAlbumListView.as_view(), name='private_albums'),
	path('create-token/<slug:slug>/', views.create_token, name='create_token'),
	path('update-token/<int:pk>/', views.update_token, name='update_token'),
	path('delete-token/<int:pk>/', views.delete_token, name='delete_token'),

	path('like-photo/', views.like_photo, name='like_photo'),

]

photos/models.py
import secrets

from django.contrib.sites.models import Site
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from taggit.managers import TaggableManager
from cloudinary.models import CloudinaryField

from core.models import BasePublishModel
from blog.models import Post
from core.utils import slugify_pre_save


class Album(BasePublishModel):
	title = models.CharField(max_length=200, null=False, blank=False)
	slug = models.SlugField(null=True, blank=True, db_index=True)
	is_featured = models.BooleanField(default=False)

	def __str__(self):
		return self.title

	def get_featured_image_url(self):
		images = self.photos.all()
		if images.exists():
			try:
				featured_image = images.filter(is_featured=True).first()
				return featured_image.image.url
			except:
				featured_image = images.first()
				return featured_image.image.url
		else:
			return ''

	def get_absolute_url(self):
		return reverse('photos:album_detail', args=[self.slug])

	class Meta:
		verbose_name = 'Album'
		verbose_name_plural = 'Albums'
		ordering = ['-is_featured', '-id']


pre_save.connect(slugify_pre_save, sender=Album)


def generate_token():
	return secrets.token_urlsafe(16)[:16]


def get_default_token_expiry_date(weeks=26):
	return timezone.localtime(timezone.now()) + timezone.timedelta(weeks=weeks)


class Photo(models.Model):
	image = CloudinaryField("Image", overwrite=True, resource_type="image", transformation={"quality": "auto:eco"})
	description = models.TextField(null=True, blank=True)
	album = models.ForeignKey(Album, on_delete=models.SET_NULL, null=True, blank=True, related_name="photos")
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post_photos", null=True, blank=True)
	title = models.CharField(max_length=250, null=True, blank=True)
	tags = TaggableManager(blank=True, help_text=None)
	alt = models.CharField(max_length=60, default="error.jpg")
	slug = models.SlugField(null=True, blank=True, unique=True, db_index=True)
	is_featured = models.BooleanField(default=False)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.title:
			self.title = self.image.name
		super(Photo, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('photos:photo_detail', args=[self.id])

	class Meta:
		verbose_name = "photo"
		verbose_name_plural = "photos"
		ordering = ['-id']


pre_save.connect(slugify_pre_save, sender=Photo)


class AlbumToken(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name='album_token')
	token = models.CharField(max_length=255, default=generate_token)
	creation_date = models.DateTimeField(auto_now_add=True)
	expiry_date = models.DateTimeField(default=get_default_token_expiry_date)

	def __str__(self):
		return f"Token #{self.id} for '{self.album.title}'"

	def is_expired(self):
		return self.expiry_date > timezone.now()

	def get_absolute_url(self):
		return reverse('photos:private_album', args=[self.token])

	def get_full_url(self):
		domain = Site.objects.get_current().domain
		path = self.get_absolute_url()
		url = f'http://{domain}{path}'
		return url

	class Meta:
		verbose_name = 'Album Token'
		verbose_name_plural = 'Albums Tokens'


def create_private_photos(sender, instance, *args, **kwargs):
	album = instance.album
	for photo in album.photos.all():
		PrivatePhoto.objects.create(
			album_token=instance,
			photo=photo
		)


post_save.connect(create_private_photos, sender=AlbumToken)


class PrivatePhoto(models.Model):
	album_token = models.ForeignKey(AlbumToken, on_delete=models.CASCADE, related_name='album_token')
	photo = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name='private_photo')
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return f""

photos/forms.py
from django import forms

from .models import Photo, Album, AlbumToken


class PhotoForm(forms.ModelForm):
	class Meta:
		model = Photo
		fields = '__all__'


PhotoFormSet = forms.modelformset_factory(
	Photo, fields=('title', 'album', 'tags', 'image', 'is_featured'), extra=1)


class AlbumForm(forms.ModelForm):
	class Meta:
		model = Album
		fields = ['title', 'status', 'is_featured']


class AlbumTokenForm(forms.ModelForm):
	class Meta:
		model = AlbumToken
		fields = '__all__'
		widgets = {
			'album': forms.widgets.HiddenInput(),
			'token': forms.widgets.URLInput(attrs={'readonly': True}),
			'expiry_date': forms.widgets.DateInput(attrs={'type': 'date'})
		}

photos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone, dateformat
from django.views.generic import ListView, TemplateView, CreateView, DeleteView
from django.contrib import messages
from extra_views import InlineFormSetFactory, CreateWithInlinesView, UpdateWithInlinesView, SuccessMessageMixin
from hitcount.views import HitCountDetailView

from accounts.forms import ContactMessageForm
from blog.models import Post
from .forms import PhotoForm, PhotoFormSet, AlbumForm, AlbumTokenForm
from .models import Photo, Album, AlbumToken, PrivatePhoto


def home(request):
	return render(request, 'photos/index.html')


class HomePageView(TemplateView):
	template_name = 'photos/index.html'

	def get_context_data(self, **kwargs):
		context = super(HomePageView, self).get_context_data(**kwargs)
		latest_albums = Album.objects.published()[:7]
		latest_posts = Post.objects.published()[:7]
		context['albums'] = latest_albums
		context['posts'] = latest_posts
		return context


class PhotoDetailView(DeleteView):
	model = Photo
	template_name = 'photos/photo_detail_view.html'
	context_object_name = 'photo'


class PhotoListView(ListView):
	model = Photo
	template_name = 'photos/photo_list.html'
	context_object_name = 'photos'


class PhotoCreateView(TemplateView):
	template_name = 'photos/add_photos.html'

	def get(self, *args, **kwargs):
		formset = PhotoFormSet(queryset=Photo.objects.none())
		return self.render_to_response({'photo_formset': formset})

	def post(self, *args, **kwargs):
		formset = PhotoFormSet(data=self.request.POST)
		if formset.is_valid():
			formset.save()
			return redirect(reverse_lazy('photo_list'))
		return self.render_to_response({'photo_formset': formset})


def upload_photo(request):
	context = dict(backend_form=PhotoForm())
	if request.method == 'POST':
		form = PhotoForm(request.POST, request.FILES)
		context['posted'] = form.instance
		if form.is_valid():
			form.save()
	return render(request, 'photos/add_photo.html', context)


class AlbumCreateView(LoginRequiredMixin, CreateView):
	model = Album
	template_name = 'photos/album_create_bulk.html'
	form_class = AlbumForm
	success_url = None

	def form_valid(self, form):
		form.instance.author = self.request.user
		self.object = form.save()
		photos = self.request.FILES.getlist('photos')
		if photos:
			for photo in photos:
				Photo.objects.create(
					album=self.object,
					image=photo
				)
		messages.success(self.request, f"<b>{self.object.title}</b> created successfully")
		return HttpResponseRedirect(self.get_success_url())

	def get_success_url(self):
		return reverse_lazy('photos:album_detail', kwargs={'slug': self.object.slug})


class AlbumPhotoInlineFormset(InlineFormSetFactory):
	model = Photo
	form_class = PhotoForm
	fields = ['image', 'is_featured']
	extra_forms = 1
	can_delete = True

	def get_factory_kwargs(self):
		factory_kwargs = super().get_factory_kwargs()
		factory_kwargs.update({'extra': self.extra_forms})
		return factory_kwargs


class AlbumCreateWithInlinesView(LoginRequiredMixin, SuccessMessageMixin, CreateWithInlinesView):
	model = Album
	form_class = AlbumForm
	inlines = [AlbumPhotoInlineFormset, ]
	template_name = 'photos/album_create.html'
	success_url = None
	success_message = "Album <b>%(title)s</b> was created successfully"

	def get_success_url(self):
		return reverse_lazy('photos:album_detail', kwargs={'slug': self.object.slug})


class AlbumUpdateWithInlinesView(LoginRequiredMixin, SuccessMessageMixin, UpdateWithInlinesView):
	model = Album
	form_class = AlbumForm
	inlines = [AlbumPhotoInlineFormset, ]
	template_name = 'photos/album_update.html'
	success_message = "Album <b>%(title)s</b> was updated successfully"


class AlbumListView(ListView):
	model = Album
	template_name = 'photos/album_list.html'
	context_object_name = 'albums'

	def get_queryset(self):
		qs = super().get_queryset()
		if self.request.user.is_staff:
			return qs
		return qs.filter(status='PU')


class AlbumDetailView(HitCountDetailView):
	model = Album
	template_name = 'photos/album_detail.html'
	context_object_name = 'album'
	count_hit = True

	def get_object(self, queryset=None):
		slug = self.kwargs.get(self.slug_url_kwarg)
		album = get_object_or_404(Album, slug=slug)
		if self.request.user.is_staff:
			return album
		if album.status == 'PR':
			messages.warning(self.request, "This album is private")
			return Album.objects.none()
		elif album.status == 'DR':
			messages.warning(self.request, "This album is not yet published")
			return Album.objects.none()
		else:
			return album

	def get_context_data(self, **kwargs):
		context = super(AlbumDetailView, self).get_context_data(**kwargs)
		if self.request.user.is_staff and self.object.is_private:
			context['album_token_form'] = AlbumTokenForm(initial={'album': self.get_object()})
			album_tokens = self.object.album_token.all() or None
			context['album_tokens'] = album_tokens
		return context


class PrivateAlbumListView(ListView):
	model = Album
	template_name = 'photos/private_album_list.html'
	context_object_name = 'albums'

	def get_queryset(self):
		qs = super().get_queryset()
		return qs.filter(status='PR')


class PrivateAlbumView(HitCountDetailView):
	model = Album
	template_name = 'photos/private_album.html'
	context_object_name = 'album'
	count_hit = True

	def get_object(self, queryset=None):
		token = self.kwargs.get('token', None)
		album_token = get_object_or_404(AlbumToken, token=token)
		album = album_token.album

		if album_token.expiry_date > timezone.now():
			return album
		else:
			messages.error(self.request,
						   f"Your access to the private album <b>{album.title}</b> expired on {dateformat.format(album_token.expiry_date, 'd F Y')}.")
			return Album.objects.none()

	def get_context_data(self, **kwargs):
		context = {}
		token = self.kwargs.get('token', None)
		if token:
			album_token = get_object_or_404(AlbumToken, token=token)
			context['album_token_id'] = album_token.id
			album = album_token.album
			favorite_photos_ids = []
			for photo in album.photos.all():
				private_photo = PrivatePhoto.objects.get(album_token=album_token, photo=photo)
				if private_photo.is_favorite:
					favorite_photos_ids.append(photo.id)
			context['favorite_photos'] = favorite_photos_ids
		context.update(kwargs)
		return super().get_context_data(**context)


class AlbumDeleteView(DeleteView):
	model = Album
	success_url = reverse_lazy('photos:albums')


class SearchView(TemplateView):
	template_name = 'photos/search_results.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		query = self.request.GET.get('q')
		posts = Post.objects.distinct().filter(
			Q(title__icontains=query) | Q(text__icontains=query) | Q(tags__name__icontains=query))
		albums = Album.objects.distinct().filter(Q(title__icontains=query))
		if not posts.exists() and not albums.exists():
			messages.error(self.request, f"No search results for <b>{query}</b>")
		else:
			context['posts'] = posts
			context['albums'] = albums
			messages.success(self.request, f"Search results for <b>{query}</b>")
		return context


def create_token(request, slug):
	album = get_object_or_404(Album, slug=slug)  # Album.objects.get(slug=slug)
	if request.method == 'POST':
		form = AlbumTokenForm(request.POST)
		if form.is_valid():
			form.save(commit=False)
			form.save()
			messages.success(request, "New token created successfully")
			return HttpResponseRedirect(reverse('photos:album_detail', args=(album.slug,)))
	return HttpResponseRedirect(reverse('photos:album_detail', args=(album.slug,)))


def update_token(request, pk):
	token = AlbumToken.objects.get(id=pk)
	album = token.album
	form = AlbumTokenForm(request.POST or None, instance=token)

	if form.is_valid():
		form.save()
		messages.success(request, f"Token updated successfully")
		return redirect(reverse_lazy('photos:album_detail', kwargs={'slug': album.slug}))
	return redirect(reverse_lazy('photos:album_detail', kwargs={'slug': album.slug}))


def delete_token(request, pk):
	token = AlbumToken.objects.get(id=pk)
	album = token.album
	token.delete()
	messages.success(request, "Token deleted successfully")
	return redirect(reverse_lazy('photos:album_detail', kwargs={'slug': album.slug}))


def like_photo(request):
	if request.POST.get('action') == 'post':
		photo_id = int(request.POST.get('photo_id'))
		photo = get_object_or_404(Photo, id=photo_id)
		album_token_id = int(request.POST.get('album_token_id'))
		album_token = get_object_or_404(AlbumToken, id=album_token_id)
		private_photo = get_object_or_404(PrivatePhoto, album_token=album_token, photo=photo)

		if private_photo.is_favorite:
			private_photo.is_favorite = False
			private_photo.save()
		else:
			private_photo.is_favorite = True
			private_photo.save()
		return JsonResponse({'is_liked': private_photo.is_favorite, 'photo_id': photo_id, })

templates/photos/add_photo.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load cloudinary %}

{% block content %}
    <div class="container global-container">

        {% include 'includes/messages.html' %}

        <div id='backend_upload' class="white-box mt-3">
            <h1>Add New Photo</h1>
            <hr class="half-gradient-hr">
            <form class="form-container" action="{% url "photos:add_photo" %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {% crispy backend_form %}
                <input type="submit" value="Upload">
            </form>
        </div>
    </div>
{% endblock %}

templates/photos/add_photos.html
{% extends '_base.html' %}

{% load cloudinary %}
{% load crispy_forms_tags %}

{% block title %}
    Add Photos
{% endblock %}

{% block content %}
    {% include 'includes/small_header.html' %}
    <div class="container" style="max-width: 650px">
        <h1>Add New Photos</h1>
        <a href="{% url 'photos:photo_list' %}">Latest Photos</a>
        <form id="form-container" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ photo_formset.management_form }}
            {% for form in photo_formset %}
                <div class="photo-form">
                    {{ form|crispy }}
                </div>
                <hr>
                <p></p>
            {% endfor %}

            <div class="d-grid gap-2">
                <button class="btn btn-outline-primary" id="add-form" type="button">Add More</button>
                <button class="btn btn-primary" type="submit">Upload Photos</button>
            </div>
        </form>


        <script>
            let photoForm = document.querySelectorAll(".photo-form")
            let container = document.querySelector("#form-container")
            let addButton = document.querySelector("#add-form")
            let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

            let formNum = photoForm.length - 1
            addButton.addEventListener('click', addForm)

            function addForm(e) {
                e.preventDefault()

                let newForm = photoForm[0].cloneNode(true)
                let formRegex = RegExp(`form-(\\d){1}-`, 'g')

                formNum++
                newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
                container.insertBefore(newForm, addButton)

                totalForms.setAttribute('value', `${formNum + 1}`)
            }
        </script>

    </div>
{% endblock %}

templates/photos/album_detail.html
{% extends '_base.html' %}
{% load comments comments_xtd social_share hitcount_tags crispy_forms_filters %}

{% block title %}
    {{ album.title|title }}
{% endblock %}

{% block stylesheet %}
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css"
    />
{% endblock %}

{% block content %}
    <div class="global-container">
        {% include 'includes/messages.html' %}

        {% if album %}

            <div class="container text-center">
                <h1>{{ album.title|title }}</h1>
                <hr class="half-gradient-hr">
                <div class="mb-5">
                    <div>
                        {% if request.user.is_authenticated and request.user.is_staff %}
                            <div class="d-flex justify-content-center align-items-center mb-2">
                                <a class="action-button edit-button" data-tooltip="Edit album"
                                   href="{% url 'photos:album_update' album.slug %}">
                                    <i class="bi bi-pencil-square"></i></a>

                                <a class="action-button delete-button" data-tooltip="Delete album"
                                   href="{% url 'photos:album_delete' album.slug %}">
                                    <i class="bi bi-trash"></i></a>

                                {% if album.is_private %}

                                    <a class="action-button private-share-button" data-bs-toggle="modal"
                                       href="#albumTokensModal" data-tooltip="Album tokens"
                                       role="button"><i class="bi bi-shield-lock"></i></a>

                                    <!-- Album Token Modal -->
                                    <div class="modal fade" id="albumTokensModal"
                                         aria-labelledby="albumTokensModalLabel" aria-hidden="true">
                                        <div class="modal-dialog modal-lg modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" id="albumTokensModalLabel">Generated Tokens
                                                        for
                                                        <b>{{ album.title|title }}</b></h4>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                            aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <table class="table table-hover">
                                                        <thead>
                                                        <tr>
                                                            <th scope="col">Token Url</th>
                                                            <th scope="col">Expiry Date</th>
                                                            <th scope="col">Action</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        {% for token in album_tokens %}
                                                            <tr>
                                                                <form action="{% url 'photos:update_token' token.id %}"
                                                                      method="post">
                                                                    <td id="privateAlbumTokenUrl{{ forloop.counter }}"
                                                                        class="album-token-url">
                                                                        {{ token.get_full_url }}</td>
                                                                    <td>{{ token.expiry_date|date:"d M Y" }}</td>

                                                                    <td>
                                                                        <div class="d-flex justify-content-around">
                                                                            <i class="bi bi-link"
                                                                               style="color:blue; font-size: 20px; cursor:pointer;"
                                                                               onclick="location.href='{% url 'photos:private_album' token.token %}';"
                                                                               data-tooltip="Got to private album"
                                                                            ></i>
                                                                            <i class="bi bi-files"
                                                                               style="color:green; font-size: 20px; cursor:pointer;"
                                                                               onclick=" copyToClipboard('privateAlbumTokenUrl{{ forloop.counter }}')"
                                                                               data-tooltip="Copy link"
                                                                            ></i>
                                                                            <i class="bi bi-trash"
                                                                               style="color:red; font-size: 20px; cursor:pointer;"
                                                                               data-tooltip="Remove token"
                                                                               onclick="location.href='{% url 'photos:delete_token' token.id %}';"
                                                                            ></i>

                                                                        </div>
                                                                    </td>
                                                                </form>
                                                            </tr>

                                                        {% empty %}
                                                            <b2>No album tokens</b2>
                                                        {% endfor %}
                                                        </tbody>
                                                    </table>

                                                </div>
                                                <div class="modal-footer">

                                                    <button type="button" class="btn btn-outline-secondary"
                                                            data-bs-dismiss="modal">
                                                        Close
                                                    </button>

                                                    <button type="button" class="btn btn-primary"
                                                            data-bs-target="#createTokenModal" data-bs-toggle="modal"
                                                            data-bs-dismiss="modal">Create new token
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Album Token Creation Modal -->
                                    <div class="modal fade" id="createTokenModal" aria-hidden="true"
                                         aria-labelledby="createTokenModalLabel" tabindex="-1">
                                        <div class="modal-dialog modal-lg modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="createTokenModalLabel">Share Private
                                                        Album</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                            aria-label="Close"></button>
                                                </div>
                                                <form action="{% url 'photos:create_token' album.slug %}" method="post">
                                                    <div class="modal-body row">
                                                        <h3 class="mb-5">Create new token for album
                                                            <b>{{ album.title|title }}</b></h3>
                                                        {% csrf_token %}
                                                        {{ album_token_form.album }}
                                                        <div class="col-6">{{ album_token_form.token|as_crispy_field }}</div>
                                                        <div class="col-6">{{ album_token_form.expiry_date|as_crispy_field }}</div>

                                                        <div class="col-12">
                                                            <button type="submit" class="btn btn-success mt-5 float-end"
                                                            >Create token
                                                            </button>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-outline-secondary"
                                                                data-bs-dismiss="modal" data-bs-toggle="modal">
                                                            Close
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    </div>

                                {% endif %}
                            </div>
                        {% endif %}


                    <section class="album-container">
                        <div class="masonry masonry--h">
                            {% for photo in album.photos.all %}
                                <figure class="masonry-brick masonry-brick--h">
                                    <a data-fancybox="gallery" href="{{ photo.image.url }}"><img
                                            src="{{ photo.image.url }}"
                                            alt="" class="masonry-img"></a>
                                </figure>
                            {% endfor %}
                        </div>
                    </section>
                    {% if album.is_published %}
                        <div>
                            {% post_to_facebook object_or_url "Share on Facebook" %}
                            {% post_to_whatsapp object_or_url "Share via WhatsApp" %}
                        </div>
                    {% endif %}
                </div>

            </div>
        {% endif %}
    </div>


{% endblock content %}

{% block javascript %}
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.umd.js"></script>
{% endblock javascript %}